#!/bin/bash
REPO="https://raw.githubusercontent.com/matteolc/react-admin-template/master/"

copy_from_git () {
  src_filename=$1;
  dst_filename=$1;
  [ -e $dst_filename ] && rm $dst_filename;
  wget "${REPO}${src_filename}" -O $dst_filename  
}

install_excel () {
  [ ! -d app/src/button ] && mkdir app/src/button
  [ ! -d app/src/component ] && mkdir app/src/component
  button_files=('DownloadButton')
  component_files=('ActionsWithExcel' 'ExportToExcel' 'ImportFromExcel')
  input_files=('FileInput')
  for file in "${button_files[@]}"
  do
   copy_from_git "app/src/button/${file}.js"
  done
  for file in "${component_files[@]}"
  do
   copy_from_git "app/src/component/${file}.js"
  done  
  for file in "${input_files[@]}"
  do
   copy_from_git "app/src/input/${file}.js"
  done
  cd app && yarn add axios superagent && cd ..
}

install_pdf () {
  [ ! -d app/src/component ] && mkdir app/src/component
  component_files=('PrintToPdf')
  for file in "${component_files[@]}"
  do
   copy_from_git "app/src/component/${file}.js"
  done  
  cd app && yarn add axios && cd ..
}

install_countries () {
  [ ! -d app/src/field ] && mkdir app/src/field
  root_files=('App.countries')
  resource_files=('countries' 'index.countries')
  field_files=('FlagField')
  for file in "${root_files[@]}"
  do
   copy_from_git "app/src/${file}.js"
  done 
  mv app/src/App.countries.js app/src/App.js  
  for file in "${resource_files[@]}"
  do
   copy_from_git "app/src/resources/${file}.js"
  done 
  mv app/src/resources/index.countries.js app/src/resources/index.js
  for file in "${field_files[@]}"
  do
   copy_from_git "app/src/field/${file}.js"
  done   
  cd app && yarn add react-flags
  cp -Rf node_modules/react-flags/vendor/flags public/
  cd ..
}

create-react-app app
mkdir app/src/resources
mkdir app/src/input

base_files=('App' 'authClient' 'dataClient' 'Layout' 'Menu' 'MyAccount' 'types', 'theme')
resource_files=('accounts' 'users' 'index')

for file in "${base_files[@]}"
do
   copy_from_git "app/src/${file}.js"
done
for file in "${resource_files[@]}"
do
   copy_from_git "app/src/resources/${file}.js"
done

copy_from_git 'app/public/index.html'
copy_from_git 'app/src/index.css'
copy_from_git 'app/package.json'

cd app && yarn install && cd ..

while true; do
    read -p "Do you want to add support for Excel data import & export?" yn
    case $yn in
        [Yy]* ) install_excel; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

while true; do
    read -p "Do you want to add support for PDF?" yn
    case $yn in
        [Yy]* ) install_pdf; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

while true; do
    read -p "Do you want to add support for countries?" yn
    case $yn in
        [Yy]* ) install_countries; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

cd app
echo "REACT_APP_NAME=Example" > .env
echo "REACT_APP_API_PROTOCOL=http" >> .env
echo "REACT_APP_API_ADDRESS=127.0.0.1" >> .env
echo "REACT_APP_API_PORT=5000" >> .env


